// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJT8WKVedTmOqzqqpG8yLpjw3qh3AyQn4',
    appId: '1:200282331623:web:fe7e8192c90f001dbf0542',
    messagingSenderId: '200282331623',
    projectId: 'sama-resto-e676e',
    authDomain: 'sama-resto-e676e.firebaseapp.com',
    storageBucket: 'sama-resto-e676e.firebasestorage.app',
    measurementId: 'G-H2YRDLHGWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvyTNXzcXvuur6bGLJfl4LVSbDo-SPwPA',
    appId: '1:200282331623:android:dab3a4218048acd7bf0542',
    messagingSenderId: '200282331623',
    projectId: 'sama-resto-e676e',
    storageBucket: 'sama-resto-e676e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArxwRznkxz9sLA7mBrgNrPhrIwh3OjdGw',
    appId: '1:200282331623:ios:d0fdc86a839a15b8bf0542',
    messagingSenderId: '200282331623',
    projectId: 'sama-resto-e676e',
    storageBucket: 'sama-resto-e676e.firebasestorage.app',
    iosBundleId: 'com.example.samaResto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArxwRznkxz9sLA7mBrgNrPhrIwh3OjdGw',
    appId: '1:200282331623:ios:d0fdc86a839a15b8bf0542',
    messagingSenderId: '200282331623',
    projectId: 'sama-resto-e676e',
    storageBucket: 'sama-resto-e676e.firebasestorage.app',
    iosBundleId: 'com.example.samaResto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJT8WKVedTmOqzqqpG8yLpjw3qh3AyQn4',
    appId: '1:200282331623:web:e508808d8b3732b7bf0542',
    messagingSenderId: '200282331623',
    projectId: 'sama-resto-e676e',
    authDomain: 'sama-resto-e676e.firebaseapp.com',
    storageBucket: 'sama-resto-e676e.firebasestorage.app',
    measurementId: 'G-ZR4P025GEG',
  );
}
